version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: golang_template_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: golang_template
      TZ: UTC
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  admin:
    image: adminer
    restart: always
    environment:
      - ADMINER_DESIGN=pepa-linha-dark
    depends_on: 
      - postgres
    ports:
      - 8080:8080  

volumes:
  postgres_data:
    name: golang_template_postgres_data 